apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-management
  template:
    metadata:
      labels:
        app: category-management
    spec:
      containers:
        - name: category-management
          image: 816069145944.dkr.ecr.us-east-1.amazonaws.com/ecr-dev-devops-kms:${GITHUB_SHA}
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: category-management
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: category-management